- id: terraform fmt 
  name: terraform format 
  description: formats all terraform files to meet standards
  entry: hooks/terraform-fmt.sh 
  language: script 
  files: \.tf$
  exclude: \.+.terraform\/.*$
  require_serial: true 

- id: terraform validate 
  name: terraform validate 
  description: formats all terraform files to meet standards.
  entry: hooks/terraform-validate.sh 
  language: script 
  files: \.tf$
  exclude: \.+.terraform\/.*$
  require_serial: true 

- id: terraform lint
  name: terraform validate 
  description: formats all terraform files to meet standards.
  entry: hooks/tflint.sh
  language: script 
  files: \.tf$
  exclude: \.+.terraform\/.*$
  require_serial: true 

- id: terraform docs 
  name: terraform docs
  description: Automaticlly document terraform configurations 
  entry: hooks/tfdocs.sh
  language: script 
  files: (\.tf)$
  exclude: \.+.terraform\/.*$
  require_serial: true 

- id: terraform_tfsec
  name: Terraform validate with tfsec
  description: Static analysis of Terraform templates to spot potential security issues.
  entry: terraform_tfsec.sh
  language: script
