formatter: markdown table
header-from: header.txt
sections:
  hide-all: true
  show:
    - header
    - inputs
    - outputs
sort:
  enabled: true
  by:
    - required
settings:
  indent: 4
  escape: false